import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { UserProvider } from '@auth0/nextjs-auth0/client';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thuistekoop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    
    <html lang="en" className={inter.className}>
      <UserProvider>
        <body>
          <Header />
           {children}
          <Footer />
          
       
        </body>
        </UserProvider>
      </html>
    
  );
}
